Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2022-10, with the labels that each got.

#63 COMDOX-346: Restore workflow customizations
  .github/CODE_OF_CONDUCT.md
  .github/dependabot.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .markdownlint.json
  .markdownlint.yml
  CODE_OF_CONDUCT.md
  package.json
  src/pages/gateway/create-mesh.md
  src/pages/gateway/transforms.md
  src/pages/reference/handlers/json-schema.md
  src/pages/reference/multiple-apis.md
  src/pages/reference/transforms/federation.md
  src/pages/reference/transforms/filter-schema.md
  src/pages/reference/transforms/prefix.md
  yarn.lock
Labels: enhancement

#65 Adding note about invalidating cache
  src/pages/gateway/cache-control-headers.md
  src/pages/gateway/index.md
  src/pages/index.md
Labels: bug

#67 Fix unnecessary code
  src/pages/gateway/cache-control-headers.md
Labels: editorial

#69 Update theme, link checker, yarn
  .github/workflows/test-pull-request.yml
  .yarn/releases/yarn-3.2.2.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, dependencies

#68 Add source install command docs
  src/pages/gateway/command-reference.md
  src/pages/gateway/create-mesh.md
  src/pages/gateway/source-handlers.md
  src/pages/reference/handlers/json-schema.md
Labels: enhancement
