Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-02, with the labels that each got.

#94 CEXT-1100 selectQueryOrMutationField is unsupported
  src/pages/reference/handlers/openapi.md
Labels: bug, documentation, editorial

#97 Updating main index page
  src/data/navigation/sections/gateway.js
  src/pages/_images/home-bg.jpeg
  src/pages/index.md
Labels: enhancement, major-update

#95 Linking to tutorials
  src/data/navigation/sections/gateway.js
Labels: documentation, enhancement, editorial

#96 CEXT-1465 Defining Content Types
  src/pages/gateway/headers.md
Labels: bug, documentation, enhancement

#100 Feb release
  src/data/navigation/sections/gateway.js
  src/pages/gateway/headers.md
  src/pages/gateway/release-notes.md
  src/pages/gateway/upgrade.md
  src/pages/gateway/work-with-mesh.md
  src/pages/reference/handlers/openapi.md
Labels: documentation, enhancement, major-update, new-topic

#101 Fixing an omitted bullet
  src/pages/gateway/release-notes.md
Labels: editorial

#102 Add indexing workflow
  .github/workflows/index.yml
Labels: enhancement

#104 Upgrade theme and gatsby versions
  package.json
  yarn.lock
Labels: maintenance
