Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-12, with the labels that each got.

#175 Batching
  src/data/navigation/sections/gateway.js
  src/pages/gateway/batching.md
Labels: technical, new-topic

#181 Fix and update workflows with a build step
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .nvmrc
  package.json
Labels: internal, maintenance

#182 Add Ext to TOC
  src/data/navigation/sections/gateway.js
Labels: editorial

#161 Fastly configuration
  src/data/navigation/sections/gateway.js
  src/pages/_images/fastly-credentials.png
  src/pages/gateway/cache-control-headers.md
  src/pages/gateway/fastly.md
  src/pages/gateway/overview.md
Labels: major-update, new-topic, internal
