Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-03, with the labels that each got.

#105 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
  yarn.lock
Labels: maintenance

#103 CEXT-1539: Updating Custom Resolvers
  .github/super-linter.env
  src/data/navigation/sections/gateway.js
  src/data/navigation/sections/reference.js
  src/pages/_examples/discounts-api.json
  src/pages/gateway/extending-unified-schema.md
  src/pages/gateway/overview.md
  src/pages/gateway/source-handlers.md
  src/pages/gateway/transforms.md
  src/pages/index.md
  src/pages/reference/extending-unified-schema.md
  src/pages/reference/handlers/graphql.md
  src/pages/reference/handlers/index.md
  src/pages/reference/handlers/json-schema.md
  src/pages/reference/handlers/openapi.md
  src/pages/reference/index.md
  src/pages/reference/multiple-apis.md
  src/pages/reference/transforms/encapsulate.md
  src/pages/reference/transforms/federation.md
  src/pages/reference/transforms/filter-schema.md
  src/pages/reference/transforms/index.md
  src/pages/reference/transforms/naming-convention.md
  src/pages/reference/transforms/prefix.md
  src/pages/reference/transforms/rename.md
  src/pages/reference/transforms/replace-field.md
  src/pages/reference/transforms/type-merging.md
Labels: major-update, new-topic

#106 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#107 March Release Notes
  src/pages/gateway/release-notes.md
Labels: major-update

#109 COMDOX-588: Update issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/incorrect_topic.yaml
  .github/ISSUE_TEMPLATE/missing_content.yaml
  .github/ISSUE_TEMPLATE/site_bug.yaml
  .github/ISSUE_TEMPLATE/site_feature.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#111 COMDOX-588: Standardized README
  README.md
Labels: maintenance

#108 Reorganizing sections in Create Mesh
  src/pages/gateway/command-reference.md
  src/pages/gateway/create-mesh.md
  src/pages/gateway/mesh_walkthrough.md
  src/pages/gateway/upgrade.md
  src/pages/gateway/work-with-mesh.md
Labels: editorial

#110 Updating release notes
  src/pages/gateway/release-notes.md
Labels: major-update

#112 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies, maintenance
