Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-09, with the labels that each got.

#159 COMDOX-345: Add topic metadata and validation test
  .github/linters/metadata.schema.yml
  .remarkrc.mjs
  package.json
  src/pages/gateway/cache-control-headers.md
  src/pages/gateway/command-reference.md
  src/pages/gateway/create-mesh.md
  src/pages/gateway/developer-tools.md
  src/pages/gateway/extending-unified-schema.md
  src/pages/gateway/getting-started.md
  src/pages/gateway/headers.md
  src/pages/gateway/hooks.md
  src/pages/gateway/index.md
  src/pages/gateway/mesh_walkthrough.md
  src/pages/gateway/overview.md
  src/pages/gateway/release-notes.md
  src/pages/gateway/source-handlers.md
  src/pages/gateway/transforms.md
  src/pages/gateway/upgrade.md
  src/pages/gateway/work-with-mesh.md
  src/pages/index.md
  src/pages/reference/combining-multiple-sources.md
  src/pages/reference/handlers/graphql.md
  src/pages/reference/handlers/index.md
  src/pages/reference/handlers/json-schema.md
  src/pages/reference/handlers/openapi.md
  src/pages/reference/handlers/soap.md
  src/pages/reference/index.md
  src/pages/reference/multiple-apis.md
  src/pages/reference/transforms/encapsulate.md
  src/pages/reference/transforms/federation.md
  src/pages/reference/transforms/filter-schema.md
  src/pages/reference/transforms/index.md
  src/pages/reference/transforms/naming-convention.md
  src/pages/reference/transforms/prefix.md
  src/pages/reference/transforms/rename.md
  src/pages/reference/transforms/replace-field.md
  src/pages/reference/transforms/type-merging.md
  yarn.lock
Labels: internal, maintenance

#160 Update Github Pages workflow
  .github/workflows/github-pages.yml
Labels: maintenance

#158 September release
  src/pages/gateway/release-notes.md
  src/pages/reference/handlers/graphql.md
  src/pages/reference/handlers/index.md
  src/pages/reference/handlers/openapi.md
  src/pages/reference/transforms/index.md
Labels: editorial, major-update

#148 Adding transform examples
  src/pages/reference/transforms/encapsulate.md
  src/pages/reference/transforms/filter-schema.md
  src/pages/reference/transforms/naming-convention.md
  src/pages/reference/transforms/prefix.md
  src/pages/reference/transforms/rename.md
  src/pages/reference/transforms/replace-field.md
Labels: editorial, major-update
