Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-10, with the labels that each got.

#163 `run` command
  src/pages/gateway/command-reference.md
  src/pages/gateway/developer-tools.md
  src/pages/gateway/release-notes.md
Labels: major-update

#165 Updating command responses
  src/pages/gateway/command-reference.md
Labels: editorial, internal

#166 Rename the test:links task
  package.json
Labels: enhancement, maintenance

#167 October bug fix
  src/pages/gateway/release-notes.md
Labels: bug, internal

#168 Security update
  src/pages/gateway/overview.md
  src/pages/gateway/release-notes.md
Labels: editorial, internal

#169 Naming convention note
  src/pages/reference/transforms/naming-convention.md
Labels: editorial, internal
