Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-01, with the labels that each got.

#79 Adding note that gRPC is unsupported
  src/pages/gateway/cache-control-headers.md
  src/pages/reference/combining-multiple-sources.md
  src/pages/reference/extending-unified-schema.md
  src/pages/reference/transforms/naming-convention.md
Labels: editorial

#88 Add nvm updates
  src/pages/gateway/getting-started.md
  src/pages/gateway/release-notes.md
  src/pages/gateway/upgrade.md
Labels: major-update, internal

#90 updating command and adding troubleshooting
  src/pages/gateway/upgrade.md
Labels: bug

#93 Removing external references
  src/pages/gateway/hooks.md
  src/pages/gateway/source-handlers.md
  src/pages/gateway/transforms.md
  src/pages/reference/handlers/graphql.md
  src/pages/reference/handlers/index.md
  src/pages/reference/handlers/json-schema.md
  src/pages/reference/handlers/openapi.md
  src/pages/reference/index.md
  src/pages/reference/transforms/index.md
  src/pages/reference/transforms/prefix.md
Labels: documentation, editorial
