Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-08, with the labels that each got.

#147 Fixing `replace-field` example
  src/pages/gateway/transforms.md
Labels: bug, editorial, technical, internal

#149 Source Note
  src/pages/gateway/create-mesh.md
  src/pages/gateway/source-handlers.md
  src/pages/reference/handlers/index.md
  src/pages/reference/handlers/json-schema.md
  src/pages/reference/handlers/openapi.md
  src/pages/reference/handlers/soap.md
Labels: editorial

#152 Aliasing release
  src/pages/gateway/release-notes.md
  src/pages/gateway/work-with-mesh.md
Labels: major-update

#155 CLI update
  src/pages/gateway/release-notes.md
  src/pages/index.md
Labels: major-update

#156 Update link
  src/pages/index.md
Labels: internal, maintenance
