Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2023-11, with the labels that each got.

#171 Update example mesh
  src/pages/gateway/create-mesh.md
Labels: technical, internal

#172 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#173 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#170 Migration branch
  src/pages/reference/index.md
Labels: editorial, internal, maintenance

#174 November release 1
  src/pages/gateway/headers.md
  src/pages/gateway/release-notes.md
Labels: major-update, internal

#177 Update caniuse-lite
  yarn.lock
Labels: dependencies

#176 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/gateway/mesh_walkthrough.md
  src/pages/gateway/overview.md
  src/pages/reference/combining-multiple-sources.md
  yarn.lock
Labels: enhancement

#178 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement
