Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2024-09, with the labels that each got.

#253 Update Fastly/API Mesh documentation
  src/pages/mesh/advanced/caching/fastly.md
  src/pages/mesh/release/index.md
  src/pages/mesh/release/update.md
Labels: major-update

#257 fixing `keep-alive` capitalization
  src/pages/mesh/advanced/secrets.md
  src/pages/mesh/basic/create-mesh.md
  src/pages/mesh/best-practices/performance.md
  src/pages/mesh/release/index.md
  src/pages/mesh/release/update.md
Labels: editorial

#258 Performance enhancements
  src/pages/mesh/best-practices/performance.md
  src/pages/mesh/release/index.md
Labels: enhancement, editorial

#261 Fastly config update
  src/pages/mesh/advanced/caching/fastly.md
Labels: editorial

#259 Request ID header
  src/pages/mesh/advanced/headers.md
Labels: editorial

#260 Next-Gen WAF configuration
  src/pages/mesh/advanced/caching/fastly.md
Labels: major-update

#252 Edge logging
  src/data/navigation/sections/mesh.js
  src/pages/_examples/bulk-logs.csv
  src/pages/mesh/advanced/hooks.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/advanced/logging.md
  src/pages/mesh/release/index.md
Labels: new-topic

#264 fixing order
  src/pages/mesh/advanced/index.md
  src/pages/mesh/release/index.md
Labels: editorial
