Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2024-04, with the labels that each got.

#199 Downgrade theme to v4.11.9
  package.json
  yarn.lock
Labels: dependencies, internal

#205 april update #2
  src/pages/gateway/release-notes.md
Labels: bug, editorial

#206 chained mutations explanation
  src/pages/gateway/work-with-mesh.md
Labels: major-update, internal
