Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2024-01, with the labels that each got.

#184 Revert the PR testing workflow
  .github/workflows/test-pull-request.yml
Labels: maintenance

#179 January release
  src/pages/gateway/command-reference.md
  src/pages/gateway/developer-tools.md
  src/pages/gateway/release-notes.md
Labels: enhancement, major-update

#185 Fixing headers
  src/pages/gateway/release-notes.md
Labels: editorial

#188 Upgrade theme to v4.11.3
  package.json
  yarn.lock
Labels: dependencies, internal

#189 January CLI Update
  src/pages/gateway/release-notes.md
Labels: bug, editorial
