Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2024-08, with the labels that each got.

#237 FIX typo
  src/pages/mesh/advanced/caching/fastly.md
Labels: editorial

#236 August release
  src/pages/mesh/advanced/secrets.md
  src/pages/mesh/release/index.md
Labels: major-update

#239 batching
  src/pages/_examples/random-discount.json
  src/pages/_images/batched.mmd
  src/pages/_images/batched.png
  src/pages/_images/unbatched.mmd
  src/pages/_images/unbatched.png
  src/pages/mesh/advanced/extend/batching.md
Labels: major-update, new-topic

#231 Edge for API Mesh
  src/_includes/migration-notice.md
  src/data/navigation/sections/mesh.js
  src/pages/_images/add-api-mesh.png
  src/pages/_images/add-api.png
  src/pages/_images/allowed-domain.png
  src/pages/_images/api-key.png
  src/pages/_images/create-project.png
  src/pages/index.md
  src/pages/mesh/advanced/caching/fastly.md
  src/pages/mesh/advanced/hooks.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/basic/create-mesh.md
  src/pages/mesh/basic/handlers/soap.md
  src/pages/mesh/basic/transforms/replace-field.md
  src/pages/mesh/best-practices/performance.md
  src/pages/mesh/edge-mesh-beta.md
  src/pages/mesh/index.md
  src/pages/mesh/release/index.md
  src/pages/mesh/release/migration.md
  src/pages/mesh/security.md
Labels: major-update

#243 Adding left-nav link
  src/data/navigation/sections/mesh.js
Labels: editorial

#232 Rearranging resolvers
  src/data/navigation/sections/mesh.js
  src/pages/_examples/random-discount.json
  src/pages/_images/batched.mmd
  src/pages/_images/batched.png
  src/pages/_images/unbatched.mmd
  src/pages/_images/unbatched.png
  src/pages/mesh/advanced/developer-tools.md
  src/pages/mesh/advanced/extend/batching.md
  src/pages/mesh/advanced/extend/index.md
  src/pages/mesh/advanced/extend/resolvers/index.md
  src/pages/mesh/advanced/extend/resolvers/programmatic-resolvers.md
  src/pages/mesh/advanced/hooks.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/basic/handlers/graphql.md
  src/pages/mesh/best-practices/index.md
  src/pages/mesh/security.md
Labels: major-update

#238 Fetch with programmatic resolvers
  src/pages/mesh/advanced/extend/batching.md
  src/pages/mesh/advanced/extend/resolvers/programmatic-resolvers.md
Labels: major-update

#245 Refactor GitHub workflows
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: maintenance

#247 Update notice
  src/_includes/migration-notice.md
  src/_includes/update-notice.md
  src/data/navigation/sections/mesh.js
  src/pages/index.md
  src/pages/mesh/basic/create-mesh.md
  src/pages/mesh/index.md
  src/pages/mesh/release/index.md
  src/pages/mesh/release/update.md
Labels: editorial

#248 Best practices for edge meshes
  src/pages/mesh/best-practices/performance.md
  src/pages/mesh/release/index.md
  src/pages/mesh/release/update.md
Labels: editorial

#249 Clarify mesh initialization
  src/pages/mesh/basic/create-mesh.md
Labels: editorial
