Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2024-07, with the labels that each got.

#223 secrets management
  src/data/navigation/sections/mesh.js
  src/pages/mesh/advanced/developer-tools.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/advanced/secrets.md
  src/pages/mesh/release/index.md
Labels: new-topic

#220 Update test-pull-request GH workflow
  .github/CODE_OF_CONDUCT.md
  .github/linters/.textlintrc
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  README.md
  src/pages/index.md
  src/pages/mesh/advanced/caching/index.md
  src/pages/mesh/advanced/developer-tools.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/basic/create-mesh.md
  src/pages/mesh/basic/handlers/json-schema.md
  src/pages/mesh/basic/transforms/rename.md
  src/pages/mesh/best-practices/cicd.md
  src/pages/mesh/best-practices/index.md
  src/pages/mesh/resources/index.md
Labels: enhancement, editorial

#228 Upgrade devDependencies
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#224 prefix clarification
  src/pages/mesh/basic/create-mesh.md
  src/pages/mesh/basic/transforms/prefix.md
Labels: editorial, internal

#230 Enable indexing on deploy
  .github/workflows/index.yml
  .github/workflows/publish.yml
Labels: internal, maintenance
