Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2025-06, with the labels that each got.

#216 Mesh template
  src/data/navigation/sections/mesh.js
  src/pages/mesh/basic/template.md
  src/pages/mesh/basic/transforms/naming-convention.md
  src/pages/mesh/release/index.md
Labels: new-topic

#329 June release #1
  src/data/navigation/sections/mesh.js
  src/pages/mesh/advanced/hooks.md
  src/pages/mesh/advanced/index.md
  src/pages/mesh/advanced/logging.md
  src/pages/mesh/basic/template.md
  src/pages/mesh/basic/transforms/naming-convention.md
  src/pages/mesh/release/index.md
Labels: major-update

#317 security description updates
  src/pages/mesh/security.md
Labels: major-update

#337 Table formatting
  src/pages/mesh/security.md
Labels: editorial

#338 Update logging.md for NewRelic forwarding with correct commands.
  src/pages/mesh/advanced/logging.md
Labels: editorial

#342 June bug fix
  src/pages/mesh/release/index.md
Labels: editorial
