Repository AdobeDocs/graphql-mesh-gateway, pull requests merged in 2025-02, with the labels that each got.

#289 Local development
  src/pages/mesh/advanced/developer-tools.md
  src/pages/mesh/release/index.md
Labels: major-update

#293 CLI update
  src/pages/mesh/release/index.md
Labels: editorial

#294 Use reusable workflow for the github-pages workflow
  .github/workflows/github-pages.yml
Labels: maintenance

#296 Logging bug fix
  src/pages/mesh/release/index.md
Labels: editorial

#297 Update GitHub workflows
  .github/workflows/test-pull-request.yml
Labels: internal, maintenance
